### ISSUE TITLE
Error at poll

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#21] opened 2021-05-17 15:40 UTC
http://dispatcher.staging.internal.odahub.io:80 "GET /run_analysis?scw_list=193200210010.001%2C193300510010.001%2C193400100010.001%2C193600090010.001%2C193600150010.001%2C193800020010.001%2C193900120010.001%2C193900160010.001%2C194000130010.001%2C194100100010.001%2C194100130010.001%2C194300090010.001%2C194400490010.001%2C194500020010.001%2C194500100010.001%2C194800270010.001%2C194800310010.001%2C194900080010.001%2C194900110010.001%2C195000330010.001&E1_keV=28.0&E2_keV=80.0&osa_version=OSA11.0&RA=275.0914266666666&DEC=7.185355&detection_threshold=7.0&instrument=isgri&product_type=isgri_image&query_type=Real&off_line=False&query_status=new&session_id=EV49GW1UN9427QD9&dry_run=False&api=True&oda_api_version=1.1.8 HTTP/1.1"

--> 556             self.poll()
    557 
    558             if not self.wait:

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in func_wrapper(*args, **kwargs)
     95         while True:
     96             try:
---> 97                 return func(*args, **kwargs)
     98             except UserError as e:
     99                 logger.exception("user error: %s", e)

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in poll(self, verbose, silent)
    498             # TODO: something raising here does not help
    499             self.logger.debug("poll returing data: complete")
--> 500             return DataCollection.from_response_json(self.response_json, self.instrument, self.product)
    501 
    502     def show_progress(self):

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in from_response_json(cls, res_json, instrument, product)
    943         elif 'numpy_data_product_list' in res_json['products'].keys():
    944 
--> 945             data.extend([NumpyDataProduct.decode(d)
    946                          for d in res_json['products']['numpy_data_product_list']])
    947 

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in <listcomp>(.0)
    943         elif 'numpy_data_product_list' in res_json['products'].keys():
    944 
--> 945             data.extend([NumpyDataProduct.decode(d)
    946                          for d in res_json['products']['numpy_data_product_list']])
    947 

~/.venv/myVE/lib/python3.8/site-packages/oda_api/data_products.py in decode(cls, encoded_obj, from_json)
    518             #print('encoded_data_unit_list',encoded_data_unit_list)
    519             for enc_data_unit in encoded_data_unit_list:
--> 520                 _data_unit_list.append(NumpyDataUnit.decode(enc_data_unit,from_json=False))
    521         else:
    522             _data_unit_list=[]

~/.venv/myVE/lib/python3.8/site-packages/oda_api/data_products.py in decode(cls, encoded_obj, use_gzip, from_json)
    367             else:
    368                 if version_info[0] > 2:
--> 369                     _data=pickle.loads(_binarys,encoding='bytes')
    370                 else:
    371                     _data = pickle.loads(_binarys)

UnpicklingError: invalid load key, '\xba'.

**Comment by volodymyrss** [comment] 2021-05-17 15:44
could you provide a piece of code that does it?

**Comment by ferrigno** [comment] 2021-05-17 15:48
https://gitlab.astro.unige.ch/integral/cc-workflows/cc-maxi1820/-/blob/master/BuildSubcases.ipynb

**Comment by volodymyrss** [comment] 2021-05-17 16:20
Ok I can reproduce it.

**Comment by ferrigno** [comment] 2021-05-17 16:30
It is code that used to work, but let me know if I should modify it

**Comment by ferrigno** [comment] 2021-05-17 20:30
I reproduced it also here:
https://github.com/oda-hub/oda_api/blob/test_poll/doc/source/user_guide/AsynchronousAPI.ipynb

**Comment by volodymyrss** [comment] 2021-05-18 10:28
for tracking, this code reproduces it quickly

```python
import logging
logging.basicConfig(level='DEBUG')
logging.getLogger('oda_api.api').setLevel('DEBUG')


import oda_api.api
disp = oda_api.api.DispatcherAPI(url="http://dispatcher.staging.internal.odahub.io")
print(disp.get_instruments_list())

disp.get_product(
    'isgri_image',
    scw_list='193200210010.001,193300510010.001,193400100010.001,193600090010.001,193600150010.001,193800020010.001,193900120010.001,193900160010.001,194000130010.001,194100100010.001,194100130010.001,194300090010.001,194400490010.001,194500020010.001,194500100010.001,194800270010.001,194800310010.001,194900080010.001,194900110010.001,195000330010.001',
    E1_keV='28.0',
    E2_keV='80.0',
    osa_version='OSA11.0',
    RA='275.0914266666666',
    DEC='7.185355',
    detection_threshold=7.0,
    instrument='isgri',
    query_type='Real',
    session_id='EV49GW1UN9427QD9',
 )
```

**Comment by volodymyrss** [comment] 2021-05-18 12:37
some peculiar data was not passed correctly, but is fixed by https://github.com/oda-hub/dispatcher-app/pull/111 and now deployed.
Please @ferrigno check and close.
Though the maxi1820 notebook fails elsewhere for me now. Maybe something is not ok in the result?

**Comment by ferrigno** [comment] 2021-05-19 23:35
I have updated the notebook, which indeed failed in fetching spi spectra. 
I had to cope with the non-public repository ccspectools

**Closed** 2021-05-19 23:35 UTC
Labels: bug

**Comment by volodymyrss** [comment] 2021-05-20 06:38
> I had to cope with the non-public repository ccspectools

But I am glad you managed! 

If you make a change, and want it to be public before it's on pypi, you can make your public fork, and put it in requirements. Also add a comment there reminding to change it later.

Quite possibly, the best location for public fork would be this one:

https://github.com/integral-observatory/ccspectools

Since it already contains cc repositories.
